### ISSUE TITLE
Better visibility for Meeting edit form field validation

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-root-server#1091]
The meeting edit form has 4 different tabs you can save a meeting on one page but get a validation error on another and not see it. We could try and auto go to tab with warning but that doesn't cover if there's multiple fields on different pages. We could add a red "bubble" on the tab header to alert of a notification. And then maybe display a message on current tab or another popup. Idk popup may be best for this.

**Comment by alanb2718** [comment]
Closed via #1111
