### ISSUE TITLE
Handling Format Deletion Options and Recommendations

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-root-server#1094]
### Deleting Formats: Considerations

When deleting formats, we have two options:  

1. **Remove the format** from any meetings that use it (clean up the database).  
2. **Prevent deletion** if the format is in use.

If we choose **Option 1**, we could:
- Warn the user that some meetings are using the format.  
- Add a visual indicator in the UI to show which meetings are affected.

leaning towards **Option 1** since there isn’t an easy way for users to manage Option 2 effectively. And seems like maybe we can fix down road by altering DB schema

**Comment by alanb2718** [comment]
Closed via #1098 and #1103 - these implement Option 1 above.
