### ISSUE TITLE
Inconsistent modal sizing for Meeting Editor

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#1133]
When editing a meeting, the modal is resized as I tab through the Basic, Location, and Other tabs. The resizing of the modal means the vertical location of the tabs changes on the screen, making it really annoying to select the next tab. It would be better if the modal were always the max vertical size.

**Comment by pjaudiomv** [comment]
It may make sense to not use modal at all and fill the meeting tabbed form where the table is

**Comment by pjaudiomv** [comment]
resolved by https://github.com/bmlt-enabled/bmlt-root-server/pull/1142
