### ISSUE TITLE
Request - Show logged in user at top of page.

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/bmlt-root-server#119]
I would like to see the user at the top of the page. Us with multiple logins it would be nice to see which one I'm logged in with and not have to log out then back in to make sure.

**Comment by jbraswell** [comment]
This makes sense to me. Maybe just change the sign out link to he “Sign Out (<username>)”?

**Comment by pjaudiomv** [comment]
I think having the username in sign out link is great idea.

**Comment by pjaudiomv** [comment]
this is in master and will be in next release
