### ISSUE TITLE
transferring meetings from Area to another Area

### ISSUE THREAD

**Issue by kcad** [bmlt-enabled/bmlt-root-server#138]
Could there be a meeting/group transfer function, when a group has moved to a different area ( within the same region ), the new area could add it ( like a copy or import ) but its put on-hold until the old area bmlt admin “approves” the move?

**Comment by radius314** [comment]
you can change the area of any meeting from the dropdown.

**Comment by kcad** [comment]
Does an Area Admin have that ability? I know as a regional admin I can but I don’t think that feature is available to an Area BMLT admin .

**Comment by radius314** [comment]
No, by design they wouldn't have that ability.  You only have access to see
areas that you have access to.  It makes sense that a regional
administrator would have the ability to do this.
