### ISSUE TITLE
PHP error: rewind() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#140]
This is just a warning, but it should probably be fixed.

PHP Warning: rewind() expects parameter 1 to be resource, array given in /var/www/html/main_server/client_interface/csv/search_results_csv.php on line 700.

This error occurs on the latest version of the root server (2.12.6)

**Comment by pjaudiomv** [comment]
I think this should probably be using reset instead of rewind.

**Comment by pjaudiomv** [comment]
fixed in 2.12.7   #144
