### ISSUE TITLE
Map Refresh Bug After Selecting "New Search."

### ISSUE THREAD

**Issue by RiftValleySoftware** [bmlt-enabled/bmlt-root-server#143]
Not sure how long this has been an issue. I just noticed it today with Denmark, and confirm that it also happens with NY.

However, it's intermittent. Sometimes, it works fine; other times, not so.

You can see it on this page: https://newyorkna.org/members/bronx-area-service/bxasc-meetings/

TO REPRODUCE:

1) Just click somewhere to get a set of markers.
2) Tap on "Specify A New Search" at the top.

When the new search page shows up, the map stops refreshing, leaving gray areas.

Like I said, I was having trouble reproducing it, but it only seems to happen after specifying a new search.

**Comment by jbraswell** [comment]
Closing this - should be moved to the https://github.com/bmlt-enabled/bmlt-wordpress-satellite-plugin repo
