### ISSUE TITLE
Warning: PHP Notice:  Undefined index: search_center

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#157]
[Tue Apr 23 20:54:21.736734 2019] [php7:notice] [pid 32365] [client 172.96.187.2:49118] PHP Notice:  Undefined index: search_center in /var/www/bmlt/main_server/client_interface/csv/csv.php on line 102

**Comment by pjaudiomv** [comment]
`getMeanLocationData` has been removed from 3.0.0 this will no longer be a thing
