### ISSUE TITLE
World ID updates from spreadsheet should also include deleted meetings

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#162]

**Comment by ChrisMarshallNY** [comment]
Just FYI. The way this works, is that if a meeting was deleted, it is not automatically added.

However, if the deleted meeting had a World ID, and was in the affected Service body, then it is included at the end, with a "D" in the "DELETE" column.

**Comment by jbraswell** [comment]
To find deleted meetings, one must crawl through the changes table. Marking as won't fix.

**Comment by radius314** [comment]
What about adding a column as suggested?

**Comment by jbraswell** [comment]
I don't like the idea of keeping deleted meetings around in the database outside of the changes table. Additionally, I think this is a low value feature.

**Comment by radius314** [comment]
#178 is a good substitute for this.

**Comment by jbraswell** [comment]
This is unrelated to #178. This is just a new feature for the bulk world ID updater. Doing #178 won't have any impact on this issue.
