### ISSUE TITLE
Format on meeting Format Page 

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/bmlt-root-server#164]
Can we change the margin on the format page so that we can use more than 3 Characters for a format code. See attached image.
<img width="1524" alt="Screen Shot 2019-05-13 at 3 53 50 PM" src="https://user-images.githubusercontent.com/50605252/57666209-f0fc7100-759a-11e9-8727-b5e43466eb78.png">

**Comment by jbraswell** [comment]
@EddieW1 How many characters are you thinking?

**Comment by EddieW1** [comment]
5 min to 7 max should do the trick.

Eddie

**Comment by pjaudiomv** [comment]
This is done and will be in next release.
