### ISSUE TITLE
Sucessful login screen not displayed

### ISSUE THREAD

**Issue by GarrettWeinberg** [bmlt-enabled/bmlt-root-server#165]
Jonathan Braswell You’ll most likely need to provide more precise reproduction steps to get an answer.

Garrett Weinberg Jonathan Braswell wish I could

Garrett Weinberg first time I ran into the issue. Billy or Adam May be able to give more detail.

Jonathan Braswell Garrett Weinberg like what is the exact URL you went to both when it did and didn’t work?

Garrett Weinberg I just started typing ctna.org/main_server and when it populated I clicked and got to the login page. Couldn’t get in.
Then I completely erased the url and typed it in fully including the https & www and then i was able to log in.

Garrett Weinberg It was like any time I used the browsers auto populate, it didn’t work

Garrett Weinberg Btw I know I’m bad at explaining things lol

Billy Woodruff Happens to me regularly. I go to https://ctna.org/main_server put in user name & password, login. Same login page reloads, no wrong password or any error. Do the same over & over. Finally I will go to History, click a link that was used previously when…See More

Billy Woodruff Some cases just adding www. To the link will work, but same issue happens if you start with https://www.ctna.org/main_server
Manage

Billy Woodruff Basically I believe a successful login screen is not coming up. Never had this problem on previous hosting provider, but has been consistent for me since switching to Inmotion. The other two who log in never seemed to have a problem, so I assumed it was just on my end, but now Garrett is experiencing it.

**Comment by jbraswell** [comment]
This appears to be an intermittent issue with Spectrum internet. We believe the unusual architecture of the root server's authentication system, specifically the giant payload that is returned on a successful login, is probably tripping some in-line security tool that Spectrum has implemented. If that's the case, there is nothing we can do about this short of rewriting authentication. I don't think this will happen until BMLT 3.x, which currently has no projected release date. I am going to close those 😢
