### ISSUE TITLE
Make semantic administration a default setting

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#169]
Seems pointless _now_ to make this an optional setting.  I recommend make this default behavior.

**Comment by pjaudiomv** [comment]
I agree

**Comment by RiftValleySoftware** [comment]
Agreed

**Comment by RiftValleySoftware** [comment]
A lot of the defaults were set the way they were, because tinfoil.

**Comment by pjaudiomv** [comment]
this is in master and will be in next release 2.13.1
