### ISSUE TITLE
Outgoing Webhooks

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#171]
I think it would be a good feature to have the ability to add a URL to the BMLT to receive updates from a specific service body (or all of them) when changes are made.  

The BMLT already today dumps information to a table and it's queryable, however, there is no notice that a change was made.  This would expand the BMLT into a new ecosystem of useful applications that could increase its adoption.

The only alternatives I've considered is writing a separate app that sits and polls for changes.  This would require a few components (a timer, a state store of some sort).  It's my belief that it would be more obviously managed through the BMLT interface.

**Comment by jbraswell** [comment]
Handling failures is usually the problem with webhooks. 

The ideal architecture is to have a daemon that sits alongside the web server that is in charge of broadcasting events to webhooks. This way they are handled asynchronously and can be retried without impacting the application. 

This is not possible with the BMLT. We can’t expect our users to be able to configure something like that, and most of their web hosts wouldn’t support it. It would have to be implemented in the same web server code that currently handles the saving or the meeting to the database. This means a save must block until a webhook notification succeeds or fails. This might be reasonable with sane timeouts but IMO is asking for difficult to debut issues. 

I like the idea of having a central service, like tomato, that polls root servers for changes, and broadcasts events about those changes to webhooks. It would need to support webhook registration, but a first version might not need a great UX for the webhook registration. 

Just my thoughts.

**Comment by jbraswell** [comment]
If the above service were built, the backend could use each Root Server’s authentication mechanism for webhook registration and management. Users could just log in with their BMLT credentials.

**Comment by radius314** [comment]
It's probably better as it's own app.
