### ISSUE TITLE
Remove "delete permanently" capability.

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#178]
We should have some discussion on this.

The existence of this button is causing some pain for the folks at NAWS who reconcile the changes with the NAWS database, and I am not clear on the value that permanently deleting a meeting provides.

A "soft delete" still removes the meeting from the meetings table, selecting "delete permanently" just prevents a change record from being written to the changes table.

@ChrisMarshallNY has the most background here. Chris, what do you think?

**Comment by ChrisMarshallNY** [comment]
I can tell you why it is there, and why I wouldn’t miss it if it were gone; but some folks might.

In the beginning, it often took multiple try’s to get a new Root Server standing, and the seed data was AWFUL.

You often needed to wipe the slate clean and try again.

Also, the reason for the “5 changes rule,” is that the change table gets really full; really quickly. The permanent delete (and it applies to other types of change records, as well), would make sure to wipe pollution away.

Remember that if you can find a meeting deletion change record, you can have Igor throw the switch, and bring the meeting back to life.

**Comment by jbraswell** [comment]
Upon further investigation, this is only available to server admins, and recent reports about issues were user error. Closing this.

**Comment by ChrisMarshallNY** [comment]
Yup. Serveradmins only.

We may want to see if there's a way that we can discourage folks from using serveradmin for routine maintenance.

**Comment by radius314** [comment]
I guess I feel like a script to delete everything or nothing at all should be the way to go.  Also deleted and unpublished lack meaning and context.  A consistent complaint from the NAWS export.

**Comment by radius314** [comment]
Per my discussion w/ @jbraswell , reviving this ticket.  We should definitely kill this feature off and instead offer up a utility script as part of the distributable that handles wipe and clean during the import process.  Otherwise, only bad things happen from having this feature remaining.  Particularly it's abuse w/intended functionality.
