### ISSUE TITLE
Sort formats on Format

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#180]
There was a request to allow for sorting on formats alphabetically on the root server administration page.

**Comment by jbraswell** [comment]
@pjaudiomv you gonna do this?

**Comment by pjaudiomv** [comment]
Damn I should of worked on this yesterday, I was but don't care if someone else does. I could probably do it tomorrow or Tuesday.

**Comment by jbraswell** [comment]
No worries. I would like to get it into the next release, and it would be good to release sometime this week. Doesn’t have to be Monday or Tuesday.

**Comment by pjaudiomv** [comment]
I did things

**Comment by pjaudiomv** [comment]
this is done and will be in next release.
