### ISSUE TITLE
UGLY UI: If You Change the Address and The Map At The Same Time, The Map Gets Ignored

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/bmlt-root-server#192]
I just ran into this with 2.13.3.

I was changing a meeting location.

Changing the address resulted in an inaccurate map, so I had to manually move the marker.

However, I did this before saving the meeting. Once I saved the meeting, the marker was moved to the inaccurate place.

Not a showstopper, as I just went in and corrected it after saving, but I could see this being an issue with some folks in a hurry.

**Comment by pjaudiomv** [comment]
yes so you would want to save the meeting, then go back move the marker and save again.

**Comment by pjaudiomv** [comment]
its def not the best workflow, but has been like this since 2.12.0 when geocode feature was added

**Comment by ChrisMarshallNY** [comment]
Not the end of the world. It won't be hit too often. I just had a meeting that had no actual street address, so I ran into it.

**Comment by ChrisMarshallNY** [comment]
If you guys want to close i=this, you can, but it is an issue; albeit a low-priority one.

The dirty flag issue is one that you should look at.

**Comment by pjaudiomv** [comment]
I agree on both points. That PR is stil a WIP so im sure jonathan will look at it. I can't remember why the workflow for that use case with geocoding and saving was like that, but do remember there wasnt really an easy solution at the time.

**Comment by jbraswell** [comment]
Fixing this appropriately is non-trivial and likely not worth the effort. This is probably better addressed through documentation and workarounds. I am going to close this - feel free to reopen in the future.
