### ISSUE TITLE
[BMLT_TABLE] Shortcode doesn't include extra information

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-root-server#193]
One of our areas has raised the issue/concern that you can't see the additional information detail when using the BMLT_TABLE display method. 
Critical information like (use the back door etc) is not included.
Is it possible to include that additional information in an extra column?

**Comment by radius314** [comment]
This should be filed under the satellite plugin.

**Comment by brustar64** [comment]
I can't see a satellite repository under BMLT enabled

[Image]




Regards
Bruce

________________________________

**Comment by ChrisMarshallNY** [comment]
https://github.com/bmlt-enabled/bmlt-wordpress-satellite-plugin

https://github.com/bmlt-enabled/bmlt-basic

https://github.com/bmlt-enabled/bmlt-drupal

However, those are just clients of the central PM class: https://github.com/bmlt-enabled/bmlt-satellite-base-class

That's where the change needs to be made.
