### ISSUE TITLE
History description not displaying

### ISSUE THREAD

**Issue by devyces** [bmlt-enabled/bmlt-root-server#197]
Changed meeting Duration, but description of event not recorded.
History entry was created with time, date and admin info, but no description of change. 
Duration change did occur and is correct in BMLT Server db.
![History Omission](https://user-images.githubusercontent.com/43420450/62437475-6054ad80-b711-11e9-8b85-105705c4152b.png)

**Comment by pjaudiomv** [comment]
Thanks Ann, I've confirmed this as well on `2.13.3`

**Comment by pjaudiomv** [comment]
`start_time` and `duration_time` not showing in change history on admin ui

**Comment by pjaudiomv** [comment]
this last worked on `2.12.8` right before the `root_server_uri` history fix

**Comment by jbraswell** [comment]
This was fixed by https://github.com/bmlt-enabled/bmlt-root-server/pull/198, and will be included in 2.13.4.

@devyces, will you help validate that this has been fixed? It will be deployed to https://latest.aws.bmlt.app/main_server/ in about 5 minutes.
