### ISSUE TITLE
It Looks Like We Return Formats in the NAWS Dump As Numerical IDs, Not As World Codes

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/bmlt-root-server#205]
This may have something to do with the new localization work.

If you look at the enclosed dump, you will see that the formats are indicated as numerical IDs.

World needs them to be strings.

[BMLT_RG371_r__gion_de_qu__bec__csrq__2019_08_13_15_59_44.csv.zip](https://github.com/bmlt-enabled/bmlt-root-server/files/3501724/BMLT_RG371_r__gion_de_qu__bec__csrq__2019_08_13_15_59_44.csv.zip)

![ScreenGrab 1](https://user-images.githubusercontent.com/51290189/63027935-d37dc280-be7b-11e9-9db6-b71ac293bbbf.png)

![ScreenGrab](https://user-images.githubusercontent.com/51290189/63027678-60744c00-be7b-11e9-9483-16da00a3d1ef.png)

**Comment by jbraswell** [comment]
Patrick and I are looking at this now, and it seems to be working fine on the NERNA server. What root server is this from? Is it using a non-english language? You are correct in that this is a serious issue and needs to be fixed ASAP. If nobody picks it up before me, I'll try and resolve this week.

**Comment by pjaudiomv** [comment]
the quebec server is 504ing right now and the cana server looks fine as well

**Comment by pjaudiomv** [comment]
the quebec server seems to have alot bigger issues than the naws format dump, there database seems corrupt. that or there server

**Comment by pjaudiomv** [comment]
also I don't see a need to prefix issues with things that labels are used for. feel free to tag a label with bug, enhancement, question etc

**Comment by ChrisMarshallNY** [comment]
Quebec has been a dicey server since Day One. It's possible they have other issues.

**Comment by ChrisMarshallNY** [comment]
Their version is 2.13.2. Was that when we added the new localization work? I'll look...

**Comment by ChrisMarshallNY** [comment]
Looks like the answer is yes. We introduced that stuff in .1.

**Comment by pjaudiomv** [comment]
I looked at a bunch of different naws dumps from different servers and have not been able to replicate yet.

**Comment by ChrisMarshallNY** [comment]
Try switching the base localization to French.
You may want to ask Claude to send you a DB dump.
https://membres.naquebec.org/reunions/main_server/semantic/
Looks like their server just nosedived again...

**Comment by ChrisMarshallNY** [comment]
Back up, but they do have problems. If you go to the semantic workshop for them, and try to select a Service body, the popup is empty.

**Comment by pjaudiomv** [comment]
yea I checked, France, Denmark, Italy, Germany, Arizona, Nerna, GNYR server naws dumps all look fine

**Comment by ChrisMarshallNY** [comment]
I suspect that they don't have the proper NAWS IDs for their SBs, which makes me wonder where the heck that dump came from.

**Comment by ChrisMarshallNY** [comment]
I suspect that it may be a hand-stitched, "artisanal" dump.

**Comment by ChrisMarshallNY** [comment]
I get a timeout when I try this: https://membres.naquebec.org/reunions/main_server/client_interface/csv/?switcher=GetServiceBodies

**Comment by ChrisMarshallNY** [comment]
I don't get a timeout anymore, but I still get an MT NAWS Dump Service body popup.
They seem to have the appropriate IDs in their data.
I know that, at one time, they were experimenting with having two different Root Servers: One for English, and one for French.
I told them is was a bad idea, but they may have gone and done it.

**Comment by ChrisMarshallNY** [comment]
Shit. Timeout again. I think they need to just merge into CANA. Fuck NA politics.

**Comment by radius314** [comment]
I think it's a misstatement to categorize why Quebec has its own root server from CANA.  This is more historical than one that you have described.   The factual reason is that, it hasn't happened yet.  The CANA server is still being built and being proven out.

**Comment by ChrisMarshallNY** [comment]
Fair 'nuff. We have issues in NY with a Service body that Serves a different language demographic. They can get downright hostile.

**Comment by ChrisMarshallNY** [comment]
There's definitely something whacky with that server. It seems that every other time I try to resolve a Service Bodies query, I get a timeout. The next time I try it, voila! No problem.
I suspect that there's some kind of weird security software messing around with things.

**Comment by jbraswell** [comment]
Do we think there is a real issue here? Can the issue be closed?

**Comment by ChrisMarshallNY** [comment]
I'm communicating with Claude about it now. Close the issue for now. If I see there's something we need to track down, I'll reopen it.
I think they are having server issues. Claude reports that he can't get in.

**Comment by pjaudiomv** [comment]
im re-opening this, there def was a problem that i dont think they caused

**Comment by pjaudiomv** [comment]
http://quebec.charlestonna.org/main_server/client_interface/json/?switcher=GetFormats

**Comment by pjaudiomv** [comment]
thats running latest root server version but with their dump

**Comment by pjaudiomv** [comment]
yes their is a def, problem

**Comment by pjaudiomv** [comment]
this is a

**Comment by pjaudiomv** [comment]
this is a brand new install as well http://nz.charlestonna.org/main_server/

if I go to the server formats their all defaulted to 12concepts even though they arent all 12 concepts. the `worldid_mixed` format is correct in the `na_comdef_formats` table. if you go and change a format and hit save, its saving the key number instead of naws code

**Comment by pjaudiomv** [comment]
fixed in `2.13.5`
