### ISSUE TITLE
Guiding Principles as NAWS mapping option

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/bmlt-root-server#212]
Can we get Guiding Principles (GP) as an option to map a Guiding Principles meeting?
If this is the wrong place to suggest ask this... just point me in a different direction.

Thanks :)

**Comment by jbraswell** [comment]
We should reach out to Lori to ask for a list of all NAWS codes and just get them all updated

**Comment by lucy12187** [comment]
I just sent her an email asking... knowing you might also. But when i get
it i'll pass it on to you in case you don't have it yet.
Lucy

**Comment by jbraswell** [comment]
Cool. Just paste the response here and we'll get it done.

**Comment by pjaudiomv** [comment]
eddies facebook comment
NC - No Children
CH = Closed Holidays

kevin g on slack
![Screen Shot 2019-09-19 at 2 36 55 PM](https://user-images.githubusercontent.com/34245618/65298736-8fe13d00-db3a-11e9-8f85-9bd512a2dda2.png)

**Comment by EddieW1** [comment]
I got a similar email from Lori today:

<img width="472" alt="Screen Shot 2019-09-19 at 6 22 45 PM" src="https://user-images.githubusercontent.com/50605252/65299364-f8182a80-db0a-11e9-9546-d87291dfbf13.png">

**Comment by lucy12187** [comment]
.



*code*

*Description*

BEG

Beginner/Newcomer

BT

Basic Text Study

CAN

Candlelight

CH

Closed on Holidays

CPT

12 Concepts Study

CW

Children Welcome

DISC

Discussion/Participation

GL

LGBTQ

GP

Guiding Principles Study

IP

IP Study

IW

It Works Study

JFT

Just For Today Study

LC

Living Clean Study

LIT

Literature Study

M

Men

MED

Meditation

NC

No Children

NP

No Pets/Animals allowed

QA

Questions & Answers

RA

Restricted Access

SMOK

Smoking

SPK

Speaker

STEP

Step

SWG

Step Working Guides Study

TOP

Topic

TRAD

Tradition

VAR

Format Varies

W

Women

Y

Young People
