### ISSUE TITLE
Override config option for auto geocoding of addresses

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/bmlt-root-server#224]
Would it be possible to have a config option to disable auto geocoding? Geocoding doesn't work so well in some areas of the world.

**Comment by jbraswell** [comment]
@paulnagle, this is implemented in 2.14.6. If you set `$auto_geocoding_enabled = false;` in `auto-config.inc.php`, it will no longer automatically geocode meetings and the latitude/longitude fields become editable.
