### ISSUE TITLE
Consider Changing the Farsi Label

### ISSUE THREAD

**Issue by ChrisMarshallNY** [bmlt-enabled/bmlt-root-server#237]
A fairly fundamental tenet of localization is to display language selections in the font and language the native speakers expect.

In that vein, I'd suggest changing the Roman-Character "Farsi" name to "فارسی".

If you also want to have an English translation, you could make it "فارسی (Farsi)"; but if you do that, you may want to consider changing the current ones, as well, for uniformity.

**Comment by pjaudiomv** [comment]
yes this makes sense didn't think about that and helping with the PR

**Comment by ChrisMarshallNY** [comment]
Yeah, but I should have put my note in as an issue. Sorry about that.

**Comment by pjaudiomv** [comment]
this was added in https://github.com/bmlt-enabled/bmlt-root-server/pull/239
