### ISSUE TITLE
Check/Uncheck all for meeting search

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/bmlt-root-server#242]
I would like to see a way to uncheck/check all of the service bodies for a search.

**Comment by radius314** [comment]
+1 for this feature.

**Comment by pjaudiomv** [comment]
Can't you just select the parent service body and it selects all children 👶 and grandchildren

**Comment by radius314** [comment]
That only works if there is a common parent.

**Comment by pjaudiomv** [comment]
Yea true not for step parents

**Comment by ChrisMarshallNY** [comment]
Just to make this clear: What you are asking for, is One Checkbox to Rule Them All, and in the Darkness Bind Them, right?

Maybe a checkbox on the top, left of the list, with a tag saying "All," or somesuch.

If it is checked, then every single checkbox is checked.

If it is unchecked, then every checkbox is turned off.

Should it have a "middle" state (like a "-")?

In the weekday list, I don't do this. If ANY of the checkboxes are unchecked, the main one becomes unchecked. You then need to do a 2-step process to uncheck all (check all, then uncheck all).

It's a reasonable request, and I can understand why, with the size of the TBRNA server.

**Comment by radius314** [comment]
An mvp for this could be two buttos one that checks and and another that
unchecks all.

**Comment by ChrisMarshallNY** [comment]
Maybe the "Check All" one becomes enabled if any of the boxes are unchecked, and the "Uncheck All" one becomes enabled if any of the checkboxes are unchecked, so it's entirely possible that they could spend most of their time enabled.

**Comment by radius314** [comment]
I think for an mvp none of that is required.

**Comment by ChrisMarshallNY** [comment]
So basically, they are "one-way." No checking the status of the current list? Just enabled all the time?

**Comment by ChrisMarshallNY** [comment]
That would certainly be easier to implement, and less likely to have bugs.

**Comment by radius314** [comment]
One way.  Checking the status is a nice to have but not required to achieve
the desired result.

**Comment by ChrisMarshallNY** [comment]
Understood. I agree.
