### ISSUE TITLE
JSON endpoints return urls with forward slashes escaped

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#243]
In any response endpoint on the semantic interface `/` (forward-slashes) returns as escaped.  

 https://root_server/main_server/client_interface/json/?switcher=GetFormats

Sample response:

```json
...
{
    "key_string": "TB",
    "name_string": "Testo base",
    "description_string": "Riunione concentrata sulla discussione del testo base di NA.",
    "lang": "it",
    "id": "3",
    "world_id": "",
    "root_server_uri": "https:\/\/root-server\/main_server",
    "format_type_enum": "FC1"
}
```

**Comment by pjaudiomv** [comment]
why is this  a problem?

**Comment by radius314** [comment]
Any application that is trying to consume the value which is a URL needs to run through an extra conversion step.

**Comment by pjaudiomv** [comment]
any language that can encode or decode json will properly unescape. thought not necessary to escape forward slashes it is valid json. php defaults to escaping forward slashes when json encoding. To not escape forward slashes in php we would do the following `json_encode($Rawr, JSON_UNESCAPED_SLASHES)`

# jq
```bash
curl "https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetServiceBodies" | jq --raw-output '.[0].url'
```

## Python
```python
import requests
print(requests.get('https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetServiceBodies').json()[0]['url'])
```

## PHP
```php
echo json_decode(file_get_contents("https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetServiceBodies"), true)[0]['url'];
```


## Javascript 
(for simplicity specifying string of exact bmlt response)

```javascript
let response = '[{"id":"9","parent_id":"20","name":"Unity Springs Area","description":"Unity Springs Area","type":"AS","url":"http:\/\/www.unityspringsna.org","helpline":"","world_id":"AR63340"}]'
console.log(JSON.parse(response)[0]['url'])
```

**Comment by radius314** [comment]
I get that you can do that, but it seems like an extra unnecessary step.

**Comment by pjaudiomv** [comment]
True true, I think changing this line will do it. 
https://github.com/bmlt-enabled/bmlt-root-server/blob/deaab90e0b3f2b259bbbec36186ff85f86d1e893/main_server/server/shared/Array2Json.php#L71

I'll check it out
