### ISSUE TITLE
API Key Referrer Issue

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/bmlt-root-server#244]
In order for us to make the Restricted Google API work on todayna.org we had to use a static url.

Myles believes that a wildcard should work.

Wondering if this is a bug or an intended feature?

**Comment by pjaudiomv** [comment]
Yes you can/should use wildcards when using referrer restrictions

**Comment by pjaudiomv** [comment]
https://bmlt.app/google-maps-api-keys-and-geolocation-issues/

![CA3C9CF2-E29E-4547-92CB-2E5EC71080FB](https://user-images.githubusercontent.com/34245618/69893639-8fa3b180-12e2-11ea-8e4f-7313f027dc38.png)
