### ISSUE TITLE
how to recover in a bmlt root server?

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/bmlt-root-server#270]
Well... Yep, I did it
I was trying to configure the service body and erase one that was not necessery. But I lost all meetings under this service body. How to restore it?
csa sao paulo (id 1526)

**Comment by jbraswell** [comment]
What happened? Did you delete a service body?

**Comment by abna-brasil** [comment]
> What happened? Did you delete a service body?

yep... I just think that the meetings was be migrated to other service body...

**Comment by jbraswell** [comment]
If you delete a service body, its meetings will become “orphaned”. This means the meeting still exists in the database, but is not assigned to any service body. The safest way to fix this is to create the service body again, and then manually edit each meeting to assign them to the new service body. It’s also possible to do this with a sql statement, but more risky.

**Comment by pjaudiomv** [comment]
if the meetings are orphaned he won't be able to reassign them in the ui, looks like the service body id was 1 and they all still exist here https://csa-saopaulo.org/bmlt/main_server/client_interface/csv/?switcher=GetSearchResults&services=1

**Comment by jbraswell** [comment]
Good point. In that case we should do the following. 

1. Create the new service body, and give us the id. 
2. We will give you a sql query. 
3. Run the sql query using phpmyadmin or equivalent.

**Comment by pjaudiomv** [comment]
youll have to either

1. create new service body, and change the service body Id to 1 with sql
2. create new service body and reassign all those meetings to it using sql
3. programmatically reassign all of them using semantic admin api

**Comment by pjaudiomv** [comment]
ah yes what Jonathan said

**Comment by abna-brasil** [comment]
> youll have to either
> 
> 1. create new service body, and change the service body Id to 1 with sql
> 2. create new service body and reassign all those meetings to it using sql
> 3. programmatically reassign all of them using semantic admin api

I dont know how to do it...

**Comment by pjaudiomv** [comment]
Yes so create a new service body and then give us the id or name of that service body. then we will write you a query to run in phpmysqladmin

**Comment by abna-brasil** [comment]
I already create a service body in the right place... ID 12

**Comment by jbraswell** [comment]
Okay. We will get you a sql query. If you need help running the sql query, we can get on zoom with you. 

I am not going to be available for a few hours, but we will help you get this worked out.

**Comment by abna-brasil** [comment]
> Okay. We will get you a sql query. If you need help running the sql query, we can get on zoom with you.
> 
> I am not going to be available for a few hours, but we will help you get this worked out.

you guys are great!! TKS

**Comment by abna-brasil** [comment]
> Okay. We will get you a sql query. If you need help running the sql query, we can get on zoom with you.
> 
> I am not going to be available for a few hours, but we will help you get this worked out.

Hello JB...
I saw that the data still there! Great!!

**Comment by jbraswell** [comment]
We believe this sql query will work for you, assuming you set `na` as your table prefix.

`UPDATE `na_comdef_meetings_main` SET service_body_bigint = 12 WHERE service_body_bigint = 1;`

**Comment by abna-brasil** [comment]
God save you guys!!!
Tks a lot for helping us...
