### ISSUE TITLE
translate pt-br

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/bmlt-root-server#272]
Hello everybody,

Here in Brazil we want to translate BMLT root srv to PT-BR.
Do you guys know how can we start this project?

**Comment by pjaudiomv** [comment]
Hey yes to get the root server translated, you will need to translate this file

https://github.com/bmlt-enabled/bmlt-root-server/blob/master/main_server/local_server/server_admin/lang/en/server_admin_strings.inc.php

**Comment by abna-brasil** [comment]
> Hey yes to get the root server translated, you will need to translate this file
> 
> https://github.com/bmlt-enabled/bmlt-root-server/blob/master/main_server/local_server/server_admin/lang/en/server_admin_strings.inc.php

Very good!!!
tks

**Comment by abna-brasil** [comment]
sorry to reopen...
I believe we did the file translate...
So now? Just replace old file on our server? We need to send the file for who?
Tks

**Comment by pjaudiomv** [comment]
Yes email it to admin@bmlt.app

**Comment by pjaudiomv** [comment]
did you get this translated, I never saw an email with the translations.

**Comment by abna-brasil** [comment]
> did you get this translated, I never saw an email with the translations.

I just sent to you now!! admin@bmlt.app  from suporte.web2@na.org.br

**Comment by pjaudiomv** [comment]
:) Awesome. So I will mege this in and it will be in next release.

**Comment by abna-brasil** [comment]
how to translate bmlt app ?

**Comment by pjaudiomv** [comment]
For the iOS and Android app you will need to translate this file https://github.com/bmlt-enabled/BMLTSearch/blob/master/src/assets/translations/en.json

**Comment by abna-brasil** [comment]
sended to admin@bmlt.app

**Comment by pjaudiomv** [comment]
going to leave this open till, translation is merged in.

**Comment by pjaudiomv** [comment]
If you could also translate the formats that would be great. https://github.com/bmlt-enabled/bmlt-root-server/blob/master/main_server/local_server/install_wizard/sql_files/InitialFormatsData-en.sql
 
only the `name_string` and `description_string` need to be translated. or everything to the right of 'en', '

**Comment by abna-brasil** [comment]
> If you could also translate the formats that would be great. https://github.com/bmlt-enabled/bmlt-root-server/blob/master/main_server/local_server/install_wizard/sql_files/InitialFormatsData-en.sql
> 
> only the `name_string` and `description_string` need to be translated. or everything to the right of 'en', '


Hello friends, let me ask you...
for example:

(1, 'B', NULL, 'BEG', 'en', 'Recém-chegados', 'Esta reunião tem foco nas necessidades de novos membros em NA.', 'FC3'),

Beginner = Recém-chegados

This meeting is focused on the needs of new members of NA.
translate is:
Esta reunião tem foco nas necessidades de novos membros em NA.

OK, but 
field  'B' and 'BEG' are shorts for Beginner....

What if we translate all lines as this model...
original:
(1, 'B', NULL, 'BEG', 'en', 'Beginners', 'This meeting is focused on the needs of new members of NA.', 'FC3'),

like this:
(1, 'RC', NULL, 'RCH', 'pt', 'Recém-chegado', 'Está reunião tem foco nas necessidades de novos membros de NA.', 'FC3'),

what do you think?

**Comment by pjaudiomv** [comment]
Your right the B needs to be translated that's the key string. However do not translate the BEG that is a world Id code and users don't see this, it is a universal code used by NAWS and should stay how it is so they know what type of format it is.

**Comment by pjaudiomv** [comment]
So for that example it should be

(1, 'RC', NULL, 'BEG', 'pt', 'Recém-chegado', 'Está reunião tem foco nas necessidades de novos membros de NA.', 'FC3'),

**Comment by abna-brasil** [comment]
got it

**Comment by abna-brasil** [comment]
> So for that example it should be
> 
> (1, 'RC', NULL, 'BEG', 'pt', 'Recém-chegado', 'Está reunião tem foco nas necessidades de novos membros de NA.', 'FC3'),

Hello, it's done
we add a line (53) into the scrpt that include a extra type of meeting...
Here we have 2 types of Wheelchair meetings.. total and partial access...  some places here there's accessible toilet for wheelchair users... some not... ok?
sql file sent to admin@bmlt.app

**Comment by pjaudiomv** [comment]
yes that is fine, thank you very much.
