### ISSUE TITLE
Warning: file_exists(): open_basedir restriction in effect. 

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/bmlt-root-server#274]
Hello everybody,

There's a Warning here in our server...

Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/na.org.br/bmlt.na.org.br/main_server/local_server/server_admin/lang/index.htm/name.txt) is not within the allowed path(s): (/var/www/vhosts/na.org.br/:/tmp/) in /var/www/vhosts/na.org.br/bmlt.na.org.br/main_server/server/c_comdef_server.class.php on line 216

**Comment by pjaudiomv** [comment]
This latest release should fix this issue, it also contains the translations and formats for Portuguese https://github.com/bmlt-enabled/bmlt-root-server/releases/download/2.14.7/bmlt-root-server.zip
