### ISSUE TITLE
Front End User Facing Form to submit Add/Change/Delete with admin approval to approve

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-root-server#284]
We are doing so much data entry it would be good to have some workflow automation in BMLT.
If we present a public facing form which members can add/change/delete their meetings and make a submission pending admin approval that might make our lives much easier.

If its new they could add the details and get a preview of what it would look like, submit their request which would come to admin for approval.   
If its a change they could search and select their meeting and make the updates/get a preview/submit for approval.  
If its a delete they search or their meeting select it and request a delete. 

There could be some checks and balances in place from an administrative process perspective but it would be great to move away from so much data entry.

**Comment by jbraswell** [comment]
I want to implement this in two parts: the root server, and a corresponding wordpress plugin.

The root server would be changed to include an api that accepts suggested changes to the meeting. The input to the API should be a full json representation of the meeting with the proposed changes. The proposed change (json) should be saved to a new database table. The root server should include a new UI that allows a service body admin to see all proposed changes and to accept or reject them.

The wordpress side should be a plugin that allows any user to suggest changes to a meeting. I would model it after what nerna's done with their meeting update form: https://nerna.org/meeting-update-form/.

**Comment by brustar64** [comment]
Awesome! So glad to see something being developed for this! Thanks guys!


Bruce

________________________________
