### ISSUE TITLE
NAWS Dump shorter than usual

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/bmlt-root-server#292]
[BMLT_RG281_hrscna_2020_03_31_16_26_02.csv.zip](https://github.com/bmlt-enabled/bmlt-root-server/files/4411550/BMLT_RG281_hrscna_2020_03_31_16_26_02.csv.zip)

Just got a reply from Lori regarding our latest NAWS Dump after the upgrade to Root server version 2.15.0.

When I look at the meeting page for the Hawaii Region there are 161 total meeting many have been unpublished.

When I do the dump I get a very short list which show a limited section of the current state of our server.

Not sure what changed but we need to have the dump show everything in the db not just the active meetings for Lori.

Here is the latest dump so you can see what I'm referring to:

**Comment by jbraswell** [comment]
Resolved by https://github.com/bmlt-enabled/bmlt-root-server/pull/298 and https://github.com/bmlt-enabled/bmlt-root-server/pull/299.
