### ISSUE TITLE
Add formats_comparison_operator

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/bmlt-root-server#301]
Would be nice to use additional comparisons other then AND for format searches like you can with tomato. This came up on my Area site when needing to produce a listing of meetings that have either the HY OR VM format.

**Comment by pjaudiomv** [comment]
This would be a nice feature as I have needed it before as well.

**Comment by tempsaint** [comment]
Agreed...

**Comment by jbraswell** [comment]
I think we should support something like this for pretty much all object types, not just formats

**Comment by jbraswell** [comment]
This is in 2.15.3

**Comment by tempsaint** [comment]
This worked excellently. Thank you. I was able to use formats_comparison_operator=OR to pull a custom query for two different formats. Nice job team.
