### ISSUE TITLE
Problems to open bmlt admin page

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/bmlt-root-server#302]
Hello my friends

We are facing a problem to open our bmlt admin address...

https://csa-saopaulo.org/bmlt/main_server/

When I look at inspection option shows a problem with a css file pointing to a png file using port 60414...
How to solve this issue?
![port60414](https://user-images.githubusercontent.com/61021590/84207445-c7589680-aa87-11ea-83c9-383aeb0483e5.JPG)

**Comment by pjaudiomv** [comment]
Did this happen after after an upgrade or when did this start

**Comment by abna-brasil** [comment]
there was a update to version 2.15.2. But was working fine.
What about the screenshot I sent?

**Comment by radius314** [comment]
can you export the HAR file from Chrome?

**Comment by abna-brasil** [comment]
here it is

**Comment by abna-brasil** [comment]
Hello,

Do you have something?

**Comment by abna-brasil** [comment]
Let me ask you ....
During the page load there are 2 fails...
style.css
shortcut.png
both trying to access my domain using port 60414...
Is this normal? ask for this port?
Cause when I take off this port from URL, load works

**Comment by jbraswell** [comment]
This is not normal. Something on the backend is generating a bad URL. I have some hunches about what might be going on. Is it possible to give me temporary access to upload PHP files or modify PHP files to troubleshoot?

**Comment by abna-brasil** [comment]
Sure! Cpanel? call me on whatsapp
55 11 959576453

**Comment by jbraswell** [comment]
Nice! cPanel would be fine. I’ll get WhatsApp set up and reach out. Thank you!

**Comment by abna-brasil** [comment]
ok tks

**Comment by jbraswell** [comment]
I can't reproduce the issue. https://csa-saopaulo.org/bmlt/main_server/ loads fine for me. Are you still seeing the issue?

**Comment by jbraswell** [comment]
Closing because I can't reproduce, if this is still an issue please let us know in Slack.
