### ISSUE TITLE
Ability for Regional Admins to add users on a zonal forum root server

### ISSUE THREAD

**Issue by kcad** [bmlt-enabled/bmlt-root-server#303]
We are setting up YAP for CRNA and want to be able to set up users without having to request the zonal forum admin set them up. We are increasing Triage members to our committee and want to able to manage additional accounts ( add and delete ).

**Comment by jbraswell** [comment]
This would be nontrivial to implement securely due to the way the root server is designed. Doesn’t yap optionally have its own user database now? I could be wrong about that, but if it does, it could potentially be implemented in yap.

**Comment by radius314** [comment]
This is currently being implemented in yap @kcad and will be delivered in version 3.8.0.

**Comment by radius314** [comment]
You may want to consider closing this in favor of that, because it would solve your issue.
