### ISSUE TITLE
Swap in croutonjs for observer view.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#311]

**Comment by jbraswell** [comment]
I _think_ when this is done we can totally remove the satellite and satellite base class from the root server.

**Comment by radius314** [comment]
What about the bmlt-basic thing?

**Comment by jbraswell** [comment]
If no code paths are using it it can be removed as well.

**Comment by pjaudiomv** [comment]
yea bmlt-basic can still use them but they aren't tied to root serever. people should just use croutonjs if they need to use the bmlt-basic

**Comment by radius314** [comment]
k, will include this as part of my PR

**Comment by jbraswell** [comment]
Yeah I mean I'm not clear on what's bundled in the root server and what's not without looking, I'm just guessing that the outcome of this issue is that there will be a ton to dead code paths and we should remove them.

**Comment by radius314** [comment]
yeah this page is the only thing that uses it.
