### ISSUE TITLE
check for whitespace in Database Connection Settings

### ISSUE THREAD

**Issue by alanborning** [bmlt-enabled/bmlt-root-server#326]
During setup, if you have a space after the Database User (or password, or database name), the database test will fail. As a minor improvement, if there is such whitespace I suggest adding a message noting that as a possible reason for the failure. (When I was first setting up a BMLT server, I futzed around for a little while trying to figure out what that problem was, and was just walking someone else through a BMLT setup last night and they had the same issue.)

If this seems like a reasonable improvement I will self assign it.

**Comment by jbraswell** [comment]
Is this because mysql does not support whitespace in usernames or passwords, or is it because the installation wizard doesn't handle whitespace correctly?

If it's that mysql doesn't support it, we should do some better client-side input validation on the installation wizard, and we should add some sanity checks with useful messages on the server side.

**Comment by alanborning** [comment]
The BMLT installation wizard currently allows for complete freedom in putting whitespace anywhere. 

Using phpMyAdmin, I could create users with whitespace at the front and back of the name, and the whitespace was present in the `CREATE USER` command, but then mysql stripped the whitespace from the front and rear before adding it to the user table. Maybe there is some other way to quote the name on the command line that would allow such spaces. I couldn't get it to add a database with whitespace at front or back, but probably it could be done from the command line by suitably quoting the name.

So here are some options:

1. Total freedom is the upmost consideration, and we should just close this issue and forget it. If users want to include spaces before or after mysql usernames, that is their essential right. It's up to them to use their freedom responsibly, and we shouldn't be implementing nanny wizards that hold their hands in doing this.
2. If the database test fails, do a check for whitespace at the front and rear of the user name, database name, and password. Add a note such as "Hint: there is whitespace after the database name. Is this what you intended?" That way they can still have the whitespace if they want it, but they get a little help tracking down this error (which, on my sample size of 2, is common among newbies).
3. Don't allow spaces at the beginning or end of user names, database names, or passwords, and check for this during setup.

I like option 2 myself.

**Comment by jbraswell** [comment]
I think I like #3, it's the same check you'd be doing in #2 except you could just do it up front.

**Comment by alanborning** [comment]
OK, option 3 it is!

**Comment by radius314** [comment]
wouldn't it make sense to just `trim()` and not have to worry about form validation?  seemingly someone could `POST` and bypass form validation.

**Comment by jbraswell** [comment]
I think username and password fields need to be precise, so I wouldn't just trim. I have created passwords with trailing white space in the past. 

I don't think anyone is going to be crafting curl commands to get through the setup wizard, but if you _really_ wanted to solve for that, you'd just validate on the server too and return an error.

**Comment by radius314** [comment]
k
