### ISSUE TITLE
setup wizard should escape single quotes in user names, passwords, and database names

### ISSUE THREAD

**Issue by alanborning** [bmlt-enabled/bmlt-root-server#327]
The auto-config.inc.php file is malformed if there is a single quote in a user name, password, or database name -- user O'Toole is out.  To fix, the setup wizard should escape single quotes.

**Comment by jbraswell** [comment]
Should we escape, or should we disallow single quotes altogether?

IMO, totally up to whoever fixes this.

**Comment by alanborning** [comment]
I was thinking escaping single quotes is better than disallowing them .... simple enough and doesn't add a restriction. I was going to fix at the same time as #326.
