### ISSUE TITLE
when deleting a user, its user id still exists in service body editors.

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-root-server#329]
When a user is deleted but not first removed as an editor from a service body, the users id still exists in the service bodies editors column. not sure weather a new user can be created or not and get the previous users id or if that auto increments.

**Comment by jbraswell** [comment]
Yeah, because the bmlt doesn't use auto increment columns (no idea why), I am pretty sure that if you deleted the user with the current max id, the next new user would get the same permissions. Good find. Shouldn't be too difficult to add logic to clean this up properly on delete.

**Comment by jbraswell** [comment]
Closing this as won't fix, because the problem will go away when we start adding proper FK relationships to the database schema.
