### ISSUE TITLE
Custom query issue

### ISSUE THREAD

**Issue by TheRichWoods** [bmlt-enabled/bmlt-root-server#346]
I'm having an issue with custom queries that's not allowing me to mix excluding and including meeting formats. First of all, this is the query I'm currently using, and it works fine:

&services%5B%5D=1001&services%5B%5D=1002&services%5B%5D=1003&services%5B%5D=1004&services%5B%5D=1067&formats%5B%5D=-54&formats%5B%5D=-55&formats_comparison_operator=OR

It's meant to exclude anything with TC or VM, therefore only showing in-person meetings. However, our website shows meetings from five areas that are from two regions, so some people are doing things differently. I noticed that some areas kept the VM format when adding the HY format, so since they still had VM, they weren't showing up on the in-person list. Naturally, I attempted to modify the custom query to exclude TC, exclude VM, and include HY.

&services%5B%5D=1001&services%5B%5D=1002&services%5B%5D=1003&services%5B%5D=1004&services%5B%5D=1067&formats%5B%5D=-54&formats%5B%5D=-55&formats%5B%5D=56&formats_comparison_operator=OR

That query did not work. Using that showed no meetings. At first I thought it might be an issue with having more than two conditions, but when I changed '56' to '-56', it filtered out the HY meetings as expected. It's definitely an issue with combining exclusion and inclusion conditions.

Root server: https://bmlt.newyorkna.org/main_server

**Comment by jbraswell** [comment]
The OR operator only works filtering meetings that have a formed, all exclude format filters are AND’d together, so this is a feature request. 

Have a look at the semantic workshop and you'll see what I mean, the UI makes it more clear - the option is only in the include section.

![image](https://user-images.githubusercontent.com/10187286/94993194-4739cd80-055d-11eb-98af-5de41a32d3d5.jpeg)

I'll take a look at the code and see if adding an OR operator for excludes is viable.

**Comment by TheRichWoods** [comment]
If you remove &formats_comparison_operator=OR the issue is still the same. There's currently no way for me to create an accurate in-person meeting list because it would have to primarily include HY, and filter out anything left that has either a TC or VM format.

**Comment by jbraswell** [comment]
Yeah, I get what you are saying. It's early and my brain is still waking up.

It seems like what you want is...

```
NOT TC AND (NOT VM OR (VM AND HY))
```

This is a nested condition, and currently there is no way to "exclude a format except when".

A feature to fix this would need a lot of thought, and I think you're better off just fixing their data and communicating to them about it for now. I would like to solve this later by just finding a better way to mark meetings as virtual or hybrid.

**Comment by jbraswell** [comment]
So basically you need to fix the data so that VM and HY are mutually exclusive.

Then the condition is...

```
NOT TC AND NOT VM
```

And that's possible using the API today.

Does that make sense?

**Comment by TheRichWoods** [comment]
Yup. Makes perfect sense. Thanks.

**Comment by jbraswell** [comment]
This is now possible by combining a  venue type filter `venue_types[]=2&venue_types[]=3` filter with a format exclude filter for TC `formats=-340`

Example: `https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&venue_types[]=2&venue_types[]=3&formats=-340`
