### ISSUE TITLE
Setup step 2 broken link

### ISSUE THREAD

**Issue by klgrimley** [bmlt-enabled/bmlt-root-server#348]
When setting up a new server the step two link [you need to register with Google](https://bmlt.app/google-maps-api-keys-and-geolocation-issues/) is a 404

**Comment by californiasteve** [comment]
I'll work on it

⁣Get BlueMail for Android ​

**Comment by pjaudiomv** [comment]
its a pretty sweet 404 page though

**Comment by klgrimley** [comment]
I mean who doesn't like seeing you eat ice cream. Should probably make that the new logo.

**Comment by jbraswell** [comment]
we need shirts

**Comment by radius314** [comment]
if your step 2 is broken, you need to go back to step 1...

**Comment by klgrimley** [comment]
@radius314 The step isn't broken. Just the referenced link to bmlt.app

**Comment by radius314** [comment]
It was an attempt at a light hearted joke.

**Comment by klgrimley** [comment]
😂  The coffee hasn't fully kicked in today

**Comment by californiasteve** [comment]
Is this during the setup installer?

**Comment by klgrimley** [comment]
Yeah, sorry. Should have included a screenshot :(
