### ISSUE TITLE
GetSearchResults filtering sequencing question

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#349]
This query returns only one result.  

`https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&services=127&recursive=1&lat_val=26.4166715&long_val=-80.085522&geo_width=-50`

It appears as though the request might be running the filters of the service body after `geo_width` is applied.  Not sure though.

**Comment by radius314** [comment]
If you increase the geo_width you get more results.  I would expect that this feature would always return results with the -50 parameter, since it's not distance related.

**Comment by jbraswell** [comment]
Just investigated this, and you are right. It's applying the `geo_width` before applying the rest of the filters. The way it does this is awkward enough that there's not an easy way to fix it.

Before running the search, it does a bunch of count queries, slowly expanding the search (without filters) until it gets to the specified number of meetings. It then draws a rectangle around that area, and remembers the north/south/east/west boundaries. Then, when doing the real query, it uses latitude and longitude comparisons in a WHERE clause to filter out all of the meetings that are not in that north/south/east/west rectangle.

I think if I were going to fix this, I'd want to figure out how to have sql calculate the `distance_in_km` and `distance_in_miles` columns, sort by one of those columns in asc order, and use `LIMIT` to limit the results. At the moment I'm not sure if mysql can do this, so I'd be limited to doing an in-memory sort post-sql to accomplish the same thing.

**Comment by jbraswell** [comment]
Until I can really do something about this... I'd probably just bump the `geo_width`. It's the only way to get it to expand the search area right now, the downside being that you are also going to get more results back.

**Comment by radius314** [comment]
Thanks for looking into this so quickly.  I have recommended to the user to increase the geo_width for now (although it would be non-deterministic in terms of an expected result set).

**Comment by jbraswell** [comment]
Actually... now that I think about it... the algorithm used by the root server should in theory work. I think the problem is that the north/south/east/west boundaries just doesn't take the service body filter into account. Instead, it only uses weekday filters. Let me see if I can figure out how to pass a service body filter down to it...

**Comment by jbraswell** [comment]
https://github.com/bmlt-enabled/bmlt-root-server/pull/350 fixes this issue
