### ISSUE TITLE
format_shared_id_list reference issue with no formats

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bmlt-root-server#353]
found in crouton 3.11.10

https://github.com/bmlt-enabled/crouton/issues/309

when `formats=""` then `format_shared_id_list` doesn't exist

**Comment by radius314** [comment]
Here is the query we used:

https://<some root server>/main_server/client_interface/json/?switcher=GetSearchResults&get_used_formats&lang_enum=en&data_field_key=location_postal_code_1,duration_time,start_time,time_zone,weekday_tinyint,service_body_bigint,longitude,latitude,location_province,location_municipality,location_street,location_info,location_text,location_neighborhood,formats,format_shared_id_list,comments,meeting_name,location_sub_province,worldid_mixed,root_server_uri,id_bigint,meeting_name,location_text,formatted_address,formatted_location_info,virtual_meeting_additional_info,virtual_meeting_additional_info,virtual_meeting_link,virtual_meeting_link,show_qrcode,virtual_meeting_link,phone_meeting_number,phone_meeting_number,show_qrcode,phone_meeting_number,latitude,longitude,latitude,longitude,map_word,latitude,longitude,contact_name_1,contact_phone_1,contact_email_1,contact_name_2,contact_phone_2,contact_email_2&services[]=1&recursive=1&sort_keys=start_time&callback=jQuery112408191614791522579_1607266783918&_=1607266783919

**Comment by jbraswell** [comment]
This should be fixed in 3.0.0.
