### ISSUE TITLE
Meeting Editor: Move VM, HY, and TC formats out of the formats tab, and into the location tab

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#355]
It should be hidden from the user doing the editing that these are formats at all. Instead, they should be options on the location tab. They should still be saved as formats in the backend, and surfaced as formats through the APIs.

Backend changes
1. Add a new `virtual_location` format_type_enum.
2. Associate VM, HY, and TC with the new `virtual` format_type_enum. This can be done in a database migration.

Frontend changes
1. Do not show `virtual_location` formats in the Formats tab.
2. Show the `virtual_location` formats in the Location tab, instead.
3. Make the `VM` and `HY` format types mutually exclusive. In other words, you can only select one.
4. Add an explanation in the UI (could be tooltip, could just be text) explaining why they are mutually exclusive.

**Comment by jbraswell** [comment]
When implementing this, make sure to review the notes from https://github.com/bmlt-enabled/bmlt-root-server/issues/363#issuecomment-742551624.

**Comment by tempsaint** [comment]
Since these will still be surfaced as formats through the APIs, this won't affect being able to filter on virtual formats in crouton, etc., right?

**Comment by jbraswell** [comment]
correct

**Comment by jbraswell** [comment]
it'll just make the existing filters more reliable... hopefully

**Comment by radius314** [comment]
So for this one, we are going to hide the formats (and other automations).  In handling the implementation of this, there are likely going to be different format codes for VM, HY, and TC.  Similar to the issue brought up in Crouton I believe about two weeks ago (https://github.com/bmlt-enabled/crouton/pull/306/files?diff=unified&w=1).  

I could seemingly target the World IDs `VM`, `HYBR`, and `TC`.
