### ISSUE TITLE
Do not allow users to save meetings without location information

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#356]
Meetings without location information have always been a problem, but they've become a _huge_ problem since virtual meetings have become a thing.

Let's make sure at least a city/state OR zip code is filled in.

We'll probably need to poke at the international servers to make sure that city/state OR zip code will work for them. If it doesn't, we'll need to change the logic, but regardless - some location information _must_ be required.

**Comment by alanborning** [comment]
Closed with 45a63b4545e5f169a3fcf3a84507754108db5e67.
