### ISSUE TITLE
Require "Virtual Meeting Link" or "Phone Meeting Dial-in Number" fields for virtual meetings

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#357]
Prerequisite: https://github.com/bmlt-enabled/bmlt-root-server/issues/355

If a user has designated the meeting as either Virtual (VM) or Hybrid (HY), do not allow them to save the meeting without entering a Virtual Meeting Link or Phone Number. Add good error messages to the UI explaining why.

**Comment by jbraswell** [comment]
For first release it might be a good idea to _warn_ the user that they should fill out either the "Virtual Meeting Link" or "Phone Meeting Dial-in Number" rather than requiring.

**Comment by alanborning** [comment]
Closed with 45a63b4545e5f169a3fcf3a84507754108db5e67.
