### ISSUE TITLE
When Virtual Meeting Link is provided, prompt user to fill out Virtual Meeting Additional Info

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#358]
Any time the user attempts to save with a non-empty Virtual Meeting Link field, and the Virtual Meeting Additional Info field is empty, we should ask them if they're sure, and explain why it's a good idea to at a minimum put the Zoom ID, password, or similar information in that field. It's fine to call out zoom specifically, let's be practical.

**Comment by radius314** [comment]
I started working on this.  Strange that the description of what the field is is actually the value

![image](https://user-images.githubusercontent.com/1850811/101969069-65244e00-3bf0-11eb-8fc1-b465174a0a57.png)

**Comment by jbraswell** [comment]
I think Virtual Meeting Link OR Phone Dial-In Information. 

There are a ton of "NA by phone" meetings out there. Idk if any of them are using BMLT presently... but would like to make them "first class citizens" along with video-based virtual meetings just in case, if it's not too much work.

**Comment by alanborning** [comment]
Easy enough to do it either way.  So I'll make it an "OR".

**Comment by alanborning** [comment]
Closed with 45a63b4545e5f169a3fcf3a84507754108db5e67.
