### ISSUE TITLE
Better document the Virtual Meeting Additional Info field inside of the UI

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#360]
Explain clearly, inside the UI, through tooltips or otherwise, what kind of information the Virtual Meeting Additional Info field should contain. It is fine to specifically call out Zoom IDs. Do not veer away from calling out a specific vendor if it is practical. Folks are smart enough to extrapolate that to other platforms.

**Comment by radius314** [comment]
Can you provide the specific message you believe should be there?

**Comment by alanborning** [comment]
How about this:

Enter any additional information for joining the virtual meeting. This should include the information needed to join the meeting by just starting the app or system -- not by using the URL in "Virtual Meeting Link" -- and entering the meeting id and so forth directly. For example, for Zoom use this format: `Zoom Meeting ID: 456 044 8613 Password: 1953`.

**Comment by jbraswell** [comment]
I think that is really good. Might shorten it a bit.

Enter any additional information for joining the virtual meeting. For example, if the meeting uses Zoom, something like `Zoom ID: 456 033 8613, Password: 1953` might be appropriate.

**Comment by alanborning** [comment]
I think we should say something to indicate that this should include the information needed to join the meeting by just starting the app or system -- not by using the URL in "Virtual Meeting Link".  If we want something shorter, how about:

Enter any additional information for joining the virtual meeting, including directly from the app. For example, if the meeting uses Zoom, `Zoom ID: 456 033 8613, Password: 1953` would be appropriate.

**Comment by jbraswell** [comment]
That works for me!

**Comment by radius314** [comment]
![image](https://user-images.githubusercontent.com/1850811/102036647-5cb74900-3d91-11eb-9d6b-40f40eb29f0e.png)

**Comment by jbraswell** [comment]
That looks really great. Only thing I'd change is putting quotes around the example message, like "Zoom ID blah blah"

**Comment by radius314** [comment]
![image](https://user-images.githubusercontent.com/1850811/102037271-c2f09b80-3d92-11eb-9416-1ec9fb22a8a6.png)
