### ISSUE TITLE
Don't allow users to edit the `virtual_location` format types

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#362]
Prerequisite: https://github.com/bmlt-enabled/bmlt-root-server/issues/355

Requirements
1. Users should not be able to add additional formats to the `virtual_location` format_type_enum.
2. Users should not be able to delete formats assigned to the `virtual_location` format_type_enum.
3. Users should not be able to change the NAWS Format or format_type_enum of formats assigned to the `virtual_location` format_type_enum.

**Comment by alanborning** [comment]
Closed with #370

**Comment by alanborning** [comment]
Sorry, this was closed prematurely. The VM, TC, and HY formats are still visible in the Format Administration tab, and we need to make sure the user can't delete them, or add new formats marked with the corresponding NAWS formats.

**Comment by radius314** [comment]
are you taking this one?

**Comment by alanborning** [comment]
Yes, can do.

**Comment by alanborning** [comment]
Closed with #394
