### ISSUE TITLE
Javascript Error 

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/bmlt-root-server#375]
When Attempting to use the new meeting browser function in the BMLT Admin section We are getting an API error. All other map functions are working correctly.

Here is the Javascript error:

<img width="1794" alt="Screen Shot 2021-01-10 at 3 17 38 PM" src="https://user-images.githubusercontent.com/50605252/104980393-8ecc5400-59aa-11eb-92ea-67b2866c9f7b.png">

And here is the URL from hitting the link inside the Admin of the BMLT:

https://todayna.org/bmlt/client_interface/html/

Please contact Myles or provide info to correctly set the Google Map API to include this link.

**Comment by jbraswell** [comment]
This is the error message google returns when the API key is not configured to allow requests from your URL.

**Comment by jbraswell** [comment]
You need to modify the HTTP Referrer restrictions on the API Key in the Google API Console. This video will show you how to get to that part of the Google API Console: https://youtube.com/watch?v=xOuwVEoWne8.

Try setting all of the following http referrer restrictions:

- todayna.org
- *.todayna.org
- todayna.org/*
- *.todayna.org/*

**Comment by EddieW1** [comment]
Thanks,

Forwarded this to Myles so He can just the API Key.

Eddie

**Comment by ChrisMarshallNY** [comment]
This issue appears closable.
