### ISSUE TITLE
switcher=GetSearchResults&get_used_formats ignores the lang_enum parameter

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/bmlt-root-server#416]
`get_used_formats` seems to ignore the `lang_enum` parameter, and instead returns a list of formats just based on the `lang_enum` for the meeting.  For example, if the meeting has `lang_enum` set to `'en'`, then the call will return the keys for the English formats, even if you call it with `switcher=GetSearchResults&get_used_formats&lang_enum=pt`.

This causes problems with crouton, which tries to display the format names and descriptions using the keys from the `lang_enum` for the meeting in the database, and the names and descriptions using the language parameter to the crouton shortcode. For example this URL displays meetings in English: https://bmlt.wszf.org/meetings/?service_body=3.  So far so good.

But see https://bmlt.wszf.org/meetings/?service_body=3&language=pt-BR.  The format names and descriptions are indeed in Portuguese.  But the keys are for the English versions of the formats -- if it happens to be the same as the Portuguese key, the format shows up, and otherwise you may not see it.  Or if the key exists in both English and Portuguese, but for different formats, you get the English key and the Portuguese description. See for example the Step Brothers meeting Wednesday at 7pm (at least in the current schedule), which has the English key M (men).  In Portuguese, the format for a women's meeting has the key M (Mulheres).

**Comment by jbraswell** [comment]
I'd be in favor changing the behavior of this to something that makes more sense, so long as it doesn't break any existing integration with bread, crouton, or the iOS app.

**Comment by ChrisMarshallNY** [comment]
I did that on purpose. The idea was that if someone was viewing a meeting in a certain language, then they would only want formats in that language.

I did not expect the situation, where there would not be formats available in the same language as the meeting. I would not expect a Portuguese speaker to want English formats in their meetings. I would expect all Portuguese-language meetings to use formats in Portuguese.

The whole format thing was kind of a mess (sorry about that, Chief). It was the first localizable data structure that I designed, and I would not do it that way again.

**Comment by alanb2718** [comment]
The problem can still arise with Portuguese-language meetings that just use Portuguese formats, if this is for example a Portuguese-speaking area in a region or zone that otherwise uses English.  (I verified this.) But it should be pretty easy to fix -- just have the server take account of the `lang_enum` parameter if present.  The only problem would be if crouton or bread are counting on the server ignoring it.
