### ISSUE TITLE
Incorrect URL in BMLT when API key is incorrectly configured

### ISSUE THREAD

**Issue by rogersearle** [bmlt-enabled/bmlt-root-server#419]
The warning link displayed at the top of the BMLT admin page after logging in, when there is an incorrectly configured API key is a 404: [https://bmlt.app/google-maps-api-keys-and-geolocation-issues/](url)
<img width="520" alt="Screen Shot 2021-05-09 at 7 19 28 AM" src="https://user-images.githubusercontent.com/55562001/117551126-3a9fc980-b098-11eb-9f22-f590e99a31d9.png">

It should be: [https://bmlt.app/google-api-key/](url)

**Comment by jbraswell** [comment]
Thank you!
