### ISSUE TITLE
Add google maps api status check for remote debugging assistance.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-root-server#42]
In order to assist with remote debugging assistance, it would be helpful to get a response back about the state of the key.  Given that the key could be restricted, this would be a valuable vantage point.

**Comment by jbraswell** [comment]
I’m not sure this will always be accurate. API keys are often restricted for use from the browser, not the server. The referrer may end up being different on the server, so you’d possibly end up with different results when testing restricted keys. A server-side test will tell us if they key will work for a meeting search that geocodes a given address string, but not if meetings can be saved in the meeting editor through a web browser.

**Comment by jbraswell** [comment]
Closing because a client side check is required to do this, and this would only provide a server side check.
