### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#435]
The `each()` function was removed in PHP 8. It's used in the formats class, probably also used elsewhere. There may also be other incompatibilities with PHP 8.

**Comment by cosmastech** [comment]
Does this need looked into further? I see there were some recent commits for PHP8 support.

**Comment by jbraswell** [comment]
Someone just needs to do a compatibility scan and then call it done.

**Comment by jbraswell** [comment]
Fully supported in the latest release AND in 3.0.
