### ISSUE TITLE
Automatically fill in the county field when a meeting is saved

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#44]

**Comment by jbraswell** [comment]
Could be in conflict with #43

**Comment by pjaudiomv** [comment]
if this does get implemented it obvs shouldnt overwrite existing data and only geocode if empty

**Comment by Redguy1959** [comment]
I would be satisfied with the County be a drop down box rather than a geocode, or at least have a drop down box override.

**Comment by pjaudiomv** [comment]
when geocoding google will return suffix of County ex. "Los Angeles County" I would also like to see that suffix removed as County is implied because the field name is County. so return just this "Los Angeles". after looking through tomato for `?switcher=GetFieldValues&meeting_key=location_sub_province` a good majority doesn't have the County suffix either.

**Comment by jbraswell** [comment]
I wonder what is returned for county for non-US locations. Do our non-US users fill out the county field at all?

**Comment by jbraswell** [comment]
If we did this, we would be disabling manual editing of the County field, and relying completely on the geocoding API to fill it in. This is probably fine 99.9% of the time in the US. My fear is that someone outside of the US may be using the field for something that wouldn’t be returned in administrative_area_level_2. I guess we could go through all of the non-US root servers in the world in tomato and see if anyone uses the field.

**Comment by pjaudiomv** [comment]
i know Ireland does

**Comment by jbraswell** [comment]
Same concerns also apply to https://github.com/bmlt-enabled/BMLT-Root-Server/issues/45

Short-term solution for both would be to only do this for US locations.

**Comment by pjaudiomv** [comment]
I don't know how much I like the idea of disabling manual entry of county or zip fields, I'd rather see just dropdown option #43 if thats the case. though that just my opinion. if there was somehow a localization option or something that could only enable this if option is set in autoconfig id feel alot better about it. but possibly degrading the system for others outside the us is not good

**Comment by jbraswell** [comment]
Yeah it’s just not possible to do this without effectively disabling manual editing of the fields unless we modify the database schema to store whether or not things are overridden.

Only filling in the County or Zip if they were previously empty is an option. 

Making this an opt-in setting could also work.

**Comment by pjaudiomv** [comment]
I like the idea of an opt in setting

**Comment by jbraswell** [comment]
So I’m seeing three options, and they’re mutually exclusive 

1. Only do this for US addresses
2. Only set the County and Zip Code fields from geocoding results when they were previously empty. 
3. Require that users opt-in to this feature with a setting.

**Comment by jbraswell** [comment]
^ updated above comment to say they’re NOT mutually exclusive

**Comment by pjaudiomv** [comment]
two and three make sense to me

**Comment by jbraswell** [comment]
I don’t think I’m comfortable doing this for non-US addresses, even on an opt-in basis. We would have to research which geocoding fields map to what users store in County and Zip for every country that uses the BMLT.

**Comment by jbraswell** [comment]
We could make that field mapping overridable with custom settings also, so that we can guide international users to use it without requiring a new root server release. This would not be difficult.

**Comment by pjaudiomv** [comment]
yea that makes sense, my feeling was use at your own risk if you choose to opt in.

**Comment by pjaudiomv** [comment]
some countries call their cities counties and all sorts of weird stuff so it would make sense if it couldnt be customized to restrict to us

**Comment by paulnagleIBM** [comment]
Addresses in countries outside of the US are formatted very differently. Disabling manual editing of the County field (or any fields) would be a serious step backwards in functionality imo.  Another point to make is that geocoding for Irish addresses only works about half of the time in my experience. At that stage I normally manually find the address on the map, and manually edit the address fields. I'd imagine this would be the case in a few other countries as well..

For example, I once moved house to a new house about 2 miles along the road. My address didnt change. The postman knew I had moved house though, so it was ok :-)

**Comment by jbraswell** [comment]
Do you think geocoding for Irish addresses works only 50% of the time because of issues with google, or because we are submitting a bad address string to them?  Curious if we can improve how we build up the address string for non-US regions.

**Comment by paulnagle** [comment]
It's kinda hard to explain how vague Irish postal addresses can be. A lot of locations will have multiple addresses, streets might have multiple names, houses will have no house numbers etc etc. Geocoding an Irish address will get you close. No fault of Google, or of the address string being passed. It's just an Irish thing.   From https://en.wikipedia.org/wiki/Postal_addresses_in_the_Republic_of_Ireland "In Ireland, 35% of Irish premises (over 600,000) have non-unique addresses due to an absence of house numbers or names"  Ireland started using postcodes (i.e. zipcodes) a couple of years ago, so improvments are on the way, but it's uncommon to be given a postcode when asked to add a meeting to the db.

**Comment by jbraswell** [comment]
It sounds like if we implement this feature it needs to be US only, opt-in, or both.

**Comment by jbraswell** [comment]
Now that auto-geocoding is configurable, it might make sense to do this.

**Comment by pjaudiomv** [comment]
if this does get implemented we should remove the appended`County` as its implied and the name of the field

**Comment by jbraswell** [comment]
k

**Comment by jbraswell** [comment]
Closed by https://github.com/bmlt-enabled/bmlt-root-server/pull/255
