### ISSUE TITLE
xml to json conversion too aggressive

### ISSUE THREAD

**Issue by nigel-bmlt** [bmlt-enabled/bmlt-root-server#457]
https://github.com/bmlt-enabled/bmlt-root-server/blob/ee6864f43e47a6a3566529f7678559bda1ec38f7/main_server/local_server/server_admin/json.php#L127

The regex on this line matches doubly embedded attributes, leading to corrupted json.

Preference for fix is to find a non regex way to handle xml attributes.

**Comment by nigel-bmlt** [comment]
example that aggresively matches (matches the closing double curly brackets against the inner @attributes object)

`
{"service_body":{"@attributes":{"id":"1","name":"Australian Region","type":"AS"},"service_body_type":"Area Service Committee","description":"Australian Region","uri":"na.org.au","helpline":"+1234","editors":{"service_body_editors":{"editor":{"@attributes":{"id":"2","admin_type":"direct","admin_name":"Meetings List Administrator"}}},"meeting_list_editors"`

**Comment by pjaudiomv** [comment]
ya there was an attempt to rewrite and fix the serialization here https://github.com/bmlt-enabled/bmlt-root-server/pull/261 but never got finished

**Comment by jbraswell** [comment]
I think realistically this happens when we rewrite the admin API

**Comment by cosmastech** [comment]
Can you help me to understand why we are using regex to parse the XML here? Could we not just iterate through elements of an array and move @attributes to the parent element?

**Comment by jbraswell** [comment]
That's just how it was written more than 10 years ago. And some of the client code now depends on this behavior, but it's not clear where. So when we fix it properly, we also need to test every client with the new output to see what breaks.

I think this and other features shouldn't happen until after we do an admin API rewrite. I have a plan. Will fill you in when we talk later.

**Comment by jbraswell** [comment]
Will be fixed in the new REST api
