### ISSUE TITLE
Rewrite: Document the endpoints used by every root server client

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#529]
Crouton, bread, yap, BMLT Search, workflow plugin, tomato, and others if I'm missing anything.

This will help us prioritize the rewrite, and will let us know what endpoints we can stop supporting.

**Comment by pjaudiomv** [comment]
| Crouton   Endpoints   | 
| ----------- | 
| client_interface/json/?switcher=GetServiceBodies  | 
| client_interface/jsonp/?switcher=GetServiceBodies |
| client_interface/serverInfo.xml |
| client_interface/json/?switcher=GetFieldKeys | 
| client_interface/json/?switcher=GetSearchResults |
| client_interface/jsonp/?switcher=GetServiceBodies |
| client_interface/jsonp/?switcher=GetFormats |

**Comment by pjaudiomv** [comment]
| Yap  Endpoints   | 
| ----------- | 
| local_server/server_admin/xml.php  | 
| local_server/server_admin/json.php |
| index.php |
| client_interface/jsonp/?switcher=GetServiceBodies |
| client_interface/jsonp/?switcher=GetServerInfo | 
| client_interface/json/?switcher=GetSearchResults |
| client_interface/jsonp/?switcher=GetFormats |
| client_interface/jsonp/?switcher=GetServiceBodies |
| client_interface/jsonp/?switcher=GetSearchResults |
| client_interface/jsonp/?switcher=GetServerInfo |

**Comment by pjaudiomv** [comment]
| Bread Endpoints   | 
| ----------- | 
| local_server/server_admin/xml.php  | 
| client_interface/json/?switcher=GetSearchResults |
| client_interface/json/?switcher=GetFieldKeys |
| client_interface/json/?switcher=GetServiceBodies |
| client_interface/json/?switcher=GetServerInfo |
| client_interface/json/?switcher=GetFormats |
| client_interface/json/?switcher=GetSearchResults |

**Comment by pjaudiomv** [comment]
| BMLT Workflow Endpoints   | 
| ----------- | 
| local_server/server_admin/xml.php  | 
| client_interface/json/?switcher=GetServerInfo |
| client_interface/json/?switcher=GetFormats |
| client_interface/jsonp/?switcher=GetSearchResults |
| client_interface/json/?switcher=GetServiceBodies |

**Comment by pjaudiomv** [comment]
I don't think anything uses `GetFieldValues` the `bmlt-satellite-base-class` does but thats legacy and i think all pulled from wordpress

**Comment by pjaudiomv** [comment]
| BMLT Portal   | 
| ----------- | 
| client_interface/xml/?switcher=GetChanges |
| client_interface/xml/?switcher=GetSearchResults |
| client_interface/json/?switcher=GetServiceBodies |

**Comment by pjaudiomv** [comment]
| Tomato Endpoints  | 
| ----------- | 
|client_interface/json/?switcher=GetServerInfo |
| client_interface/jsonl/?switcher=GetSearchResults |
| client_interface/json/?switcher=GetServiceBodies |
| client_interface/json/?switcher=GetFormats |
