### ISSUE TITLE
NAWS Import not working for 3.0.0

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-root-server#625]
I tried to initialize a sever with a naws export and received the following error. I didnt see any additional errors in the apache logs or laravel logs. This was with this build https://s3.amazonaws.com/archives.bmlt.app/bmlt-root-server/bmlt-root-server-3.0.0-build300-1b4c4f3c13605b282aa62bfdce68cfedeae7334f.zip

<img width="396" alt="Screen Shot 2022-09-24 at 8 51 34 PM" src="https://user-images.githubusercontent.com/34245618/192123857-4f266ee4-b6bd-4450-bffa-ba761fe6310c.png">

I initialized a new server and logged in and then tried to import meetings from a naws export and got this error, again couldnt see any further logs. this was with australia region export.

<img width="407" alt="Screen Shot 2022-09-24 at 8 56 22 PM" src="https://user-images.githubusercontent.com/34245618/192123882-d014941f-5204-4547-8505-43bb359765db.png">

I got this error with cape cod area export

<img width="377" alt="Screen Shot 2022-09-24 at 9 05 32 PM" src="https://user-images.githubusercontent.com/34245618/192123922-f3e056db-33cd-47a2-8e94-245fd509e441.png">

**Comment by alanb2718** [comment]
I also get the error shown in the second screenshot when trying to do a NAWS import:
`Error(s): Undefined array key "location_info"`
Will investigate.

The error message on the last screenshot (`Number of meetings updated: 0 `etc) is from a different command (`Update World Committee Codes from NAWS Spreadsheet)`.  You'd see the `WARNING: 50 meetings ...` stuff if you were trying to update the codes for meetings whose `bmlt_id`s weren't in the database.  Maybe you accidentally had the wrong command that time??

**Comment by jbraswell** [comment]
I'm looking into the installer issue while you guys look into the other issues.

**Comment by jbraswell** [comment]
The problem with the installer is that the session handler's db connection is already initialized (using the wrong default credentials), and there's no way to swap it at runtime. To do an import in the installer, we're going to have to use [laravel's http client](https://laravel.com/docs/9.x/http-client) to make http requests from the root server to itself. We'll need to authenticate as admin, and then send another request to upload the naws import file and do the import.

**Comment by alanb2718** [comment]
Should be fixed with #628 and #629 -- @pjaudiomv could you check please?

**Comment by pjaudiomv** [comment]
just tested, this totes works fine now
