### ISSUE TITLE
default_duration_time from autoconfig doesnt get respected in meeting editor

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/BMLT-Root-Server#69]
the default_duration_time from autoconfig doesnt get respected in meeting editor dropdown, im guessing it should? at least that would make since to me. the default dropdown value is a static pulled from the server admin strings. I feel like somehow we should pull from $localized_strings['default_duration_time']. im using latest version 2.12.2

maybe thats done here
https://github.com/bmlt-enabled/BMLT-Root-Server/blob/a9da7caeb9ad31494d0e4ca4f39aae27075669bf/main_server/local_server/server_admin/c_comdef_admin_main_console.class.php#L349

this is the static its currently getting pulled from
https://github.com/bmlt-enabled/BMLT-Root-Server/blob/a9da7caeb9ad31494d0e4ca4f39aae27075669bf/main_server/local_server/server_admin/lang/en/server_admin_strings.inc.php#L139

**Comment by jbraswell** [comment]
I think you'd want to fix this code in the dom template that gets printed here:

https://github.com/bmlt-enabled/BMLT-Root-Server/blob/a9da7caeb9ad31494d0e4ca4f39aae27075669bf/main_server/local_server/server_admin/c_comdef_admin_main_console.class.php#L1659-L1679

**Comment by jbraswell** [comment]
Basically you'd just add a "selected" attribute to the hour and minute options if they match the default.

`<option value="blar" selected>asdf</option>`

**Comment by jbraswell** [comment]
fixed
