### ISSUE TITLE
Feature: 3.x API for server settings

### ISSUE THREAD

**Issue by nigel-bmlt** [bmlt-enabled/bmlt-root-server#708]
As per https://github.com/bmlt-enabled/bmlt-workflow/issues/103 it is useful to know if the auto geolocate setting is enabled or disabled.

This isn't available via client_interface/json/?switcher=GetServerInfo

Looking for an equivalent API to get all configurable server settings remotely

**Comment by nigel-bmlt** [comment]
likely also need search_spec_map_center surfaced via api as well.

**Comment by pjaudiomv** [comment]
> likely also need search_spec_map_center surfaced via api as well.

This should be there already as CenterLongitude, center latitude and zoom or something like that

**Comment by pjaudiomv** [comment]
> 

geolocate was never exposed in old api but its this setting `$auto_geocoding_enabled = false;` this is a new feature request for bmlt workflow so he hadnt had to implement it before.

**Comment by pjaudiomv** [comment]
`auto_geocoding_enabled` is returned as a bool in GetServerInfo for 3.0 now. will update gyro shortly
