### ISSUE TITLE
return bmlt ids of empty field key values in semantic responses

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-root-server#74]
if i run a query say `GetFieldValues&meeting_key=location`_province I get a list of all ids for the various `location_province` values in my rootserver. but what i don't get is a list of ids that have an empty value for `location_province`. I would like to be able to get that from semantic response.

**Comment by pjaudiomv** [comment]
this field value could just be called NULL or EMPTY or whatever

**Comment by jbraswell** [comment]
Curious... does tomato behave the same way?

**Comment by pjaudiomv** [comment]
yes tomato behaves the same way

**Comment by pjaudiomv** [comment]
except for `worldid_mixed` the root server displays `NULL` in the `worldid_mixed` field value if its empty. Tomato just displays empty field value `""`

**Comment by pjaudiomv** [comment]
![Screen Shot 2019-07-06 at 9 21 29 AM](https://user-images.githubusercontent.com/34245618/60756750-7a468780-9fcf-11e9-923d-ede5be4c86ee.png)
![Screen Shot 2019-07-06 at 9 20 59 AM](https://user-images.githubusercontent.com/34245618/60756751-7a468780-9fcf-11e9-9eb0-01a545097b37.png)

**Comment by pjaudiomv** [comment]
don't think the squeeze is worth juicing on this, I have a script I use to check these.


```php
<?php

$meetingKey = $_REQUEST['meeting_key'];

$allMeetings = json_decode(file_get_contents("https://www.somedomain.org/main_server/client_interface/json/?switcher=GetSearchResults"), true);

$emptyValues[$meetingKey] = "";

foreach ($allMeetings as $meeting) {
    if (empty($meeting[$meetingKey])) {
        $emptyValues[$meetingKey] .= $meeting['id_bigint'] . ",";
    }
}

if (!empty($emptyValues)) {
    header('Content-Type:application/json; charset=UTF-8');
    echo json_encode($emptyValues);
}
```
