### ISSUE TITLE
Tomato Mode: Collect and expose root server stats

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#826]
Need to see what stats are being used, and it might be nice to add some additional stats.

**Comment by pjaudiomv** [comment]
https://github.com/bmlt-enabled/bmlt-metrics/blob/main/metrics.py#L33

**Comment by pjaudiomv** [comment]
Need to find out what tally uses

**Comment by pjaudiomv** [comment]
https://github.com/bmlt-enabled/tally/blob/master/js/tally.js#L42
