### ISSUE TITLE
Cannot copy Latitude and Longitude from text box on Location page

### ISSUE THREAD

**Issue by Redguy1959** [bmlt-enabled/bmlt-root-server#84]
I find it necessary to copy/paste longitude and latitude information that the BMLT produces for a meeting. I can no longer select and copy the numerical iformation in the box.

**Comment by jbraswell** [comment]
To fix this we could just get rid of the input fields and print the lat/long as text on the page.

**Comment by pjaudiomv** [comment]
just to clarify do you need to copy the long/lat info to paste somewhere else. or are you trying to past long/lat in the box

**Comment by pjaudiomv** [comment]
you could also just do this instead<input type="" value="" class="" readonly> add readonly to input field instead opf tottally disabling it. this would enable you to copy and paste but not to input or edit data

**Comment by jbraswell** [comment]
do eeeet

**Comment by pjaudiomv** [comment]
oh i will

**Comment by pjaudiomv** [comment]
this is in master and will be in next release.

**Comment by Redguy1959** [comment]
@pjaudiomv - to clarify, need to paste the lat/long somewhere else, not in BMLT.

**Comment by Redguy1959** [comment]
When is the next BMLT release and what will be the version number? Current is 2.12.2, correct?

**Comment by jbraswell** [comment]
The current is 2.12.3. The next will probably be 2.12.4.

https://bmlt.app/what-is-the-bmlt/get-bmlt/download/

**Comment by Redguy1959** [comment]
The Direct Download link on this page https://bmlt.app/installing-a-new-root-server/setting-up-a-root-server/ is still at 2.12.2.
  ----- Original Message -----

**Comment by jbraswell** [comment]
Thanks. We'll get that fixed.

@pjaudiomv can you take a look?

**Comment by pjaudiomv** [comment]
Cool page is somewhat updated for now I'm out of pocket so just changed it to be link to downloads page. Thanks guys!
