### ISSUE TITLE
Changing new UI to enforce user permissions

### ISSUE THREAD

**Issue by Jneville0815** [bmlt-enabled/bmlt-root-server#847]
1. Only admin users can create or delete users.
2. serviceBodyAdmin users can edit users that are owned by them (and those are also the only users they see when calling /users/), but only some fields. I think a serviceBodyAdmin just can’t change a user’s type or owner.
3. admin users can edit all fields on all users.
4. All users can edit themselves, but not their type or owner.

**Comment by alanb2718** [comment]
Addressed with #889
