### ISSUE TITLE
satellite base class static files, 404

### ISSUE THREAD

**Issue by jbraswell** [bmlt-enabled/bmlt-root-server#86]
2(index):12 GET https://bmlt.sezf.org/new_main_server/client_interface/html/bmlt-basic/BMLT-Satellite-Base-Class/themes/BlueAndWhite/style_stripper.php?filename=nouveau_map_styles.css net::ERR_ABORTED 404 (Not Found)
2(index):20 GET https://bmlt.sezf.org/new_main_server/client_interface/html/bmlt-basic/BMLT-Satellite-Base-Class/nouveau_map_search.js net::ERR_ABORTED 404 (Not Found)

**Comment by pjaudiomv** [comment]
didn't realize you self assigned
