### ISSUE TITLE
Google Maps API Key Error

### ISSUE THREAD

**Issue by Connected57** [bmlt-enabled/bmlt-root-server#865]
Hi, I'm trying to update an existing meetings location but I recieve the following error when trying to save.

![image](https://user-images.githubusercontent.com/5223400/214351054-6b1042e4-fa7c-491a-adec-d6115cee37d3.png)

Kind regards,
Aaron H.
Gold Coast Area Webmaster

**Comment by Connected57** [comment]
I recently became the Webmaster for the Central California Region so I believe this falls under me. I'll reach out to the previous Webmaster who setup the server and ask him to guide me through updating the Google API restrictions. Hopefully, he still around. If he's not, can contact you for assistance?

Kind regards,
Aaron H.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jbraswell** [comment]
Will you email your contact info to help@bmlt.app?
