### ISSUE TITLE
Cookies not being respected for get_permissions admin action.

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bmlt-root-server#885]
It was reported today by a yap user (WSZF) that they couldn't login using a BMLT user.  This relies on cookies and the get_permissions admin action. 

Essentially yap makes request to login and stores the cookie response.  https://github.com/bmlt-enabled/yap/blob/7a01761f5cba076607a3de86db909dbed39ae914/legacy/_includes/functions.php#L1897

On subsequent requests that cookie is passed back to the root server for authenticated requests.  Specifically, on login of a root server to yap, there is a request to this endpoint.

https://github.com/bmlt-enabled/yap/blob/7a01761f5cba076607a3de86db909dbed39ae914/legacy/_includes/functions.php#L1914

That request returns a `NOT AUTHORIZED` content response.

Upon further investigation, it looks like that the cookies are not working on this one request (perhaps there are others).  It only seems to happen on the WSZF root server.

Repro steps:

1. `https://bmlt.wszf.org/main_server/local_server/server_admin/json.php?c_comdef_admin_login=<username>&c_comdef_admin_password=<password>&admin_action=login`

2. `https://bmlt.wszf.org/main_server/local_server/server_admin/json.php?admin_action=get_permissions`

However this does work:

`https://bmlt.wszf.org/main_server/local_server/server_admin/json.php?c_comdef_admin_login=<username>&c_comdef_admin_password=<password>&admin_action=get_permissions`

**Comment by pjaudiomv** [comment]
FYI Hosting Provider is SiteGround

**Comment by dgershman** [comment]
The user is a service body admin.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jbraswell** [comment]
Looks like this is some kind of adaptive application firewall that SiteGround has implemented. There's nothing for us to fix here.
