### ISSUE TITLE
State and County Search not Working

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/bmlt-root-server#893]
When search using a custom query it returns all counties with that name and doesn't apply the state query.
Here's the query I'm using https://tomato.bmltenabled.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_key=location_province&meeting_key_value=MN&meeting_key=location_sub_province&meeting_key_value=Benton

**Comment by jbraswell** [comment]
This isn't a bug - can't assign two different values to the same variable names (meeting_key and meeting_key_value) at the same time.
