### ISSUE TITLE
Show accurate history for data deletions  

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-root-server#925]
When completely deleting field data the history only shows "... was deleted" instead of showing the actual text that was deleted. If the data is edited from something to something else, the history shows the actual change. It should do that when deleting all content in the field as well. 

<img width="468" alt="image" src="https://github.com/bmlt-enabled/bmlt-root-server/assets/38324357/0803395a-f702-4104-8e1e-dc36c14e9d86">

**Comment by jbraswell** [comment]
I think the data all exists in the database, so we could do this in the new UI.

**Comment by tempsaint** [comment]
> I think the data all exists in the database, so we could do this in the new UI.

Bummer - I was hoping it would be a simple change in code somewhere. I'm assuming whatever logic displays the history is looking at the previous field value and the current field value, but if the current field value is null then it just displays "... was deleted" rather than the previous content.  I'm no software engineer but the way I wrote my assumption it seems like the code might be doing something extra to display the "... was deleted" instead of just displaying the previous and current content.

**Comment by jbraswell** [comment]
You're right. That's probably how it works. All of the data is there, so we can fix it in the new UI. It's moving along, even if slowly.

Unless there are actual bugs, I essentially want to feature freeze the old UI.

This doesn't seem like a bug, but more like unfortunate UX that no one has mentioned until now.

**Comment by jbraswell** [comment]
It's possible those messages are generated in the already rewritten server side code. I honestly can't remember. If that's the case, we could fix it sooner, since the change would be in the new PHP code and not the old UI code.

**Comment by pjaudiomv** [comment]
this has been completed by merging of https://github.com/bmlt-enabled/bmlt-root-server/pull/1090 the query api will have the change in whatever next release is and UI will have it whenever new UI is released.
