### ISSUE TITLE
Fix navbar test for Service Bodies

### ISSUE THREAD

**Issue by alanb2718** [bmlt-enabled/bmlt-root-server#995]
There seems to be a problem with rendering the Service Bodies tab in the unit tests if you go via the home page and simulate clicking on the link.  See this line, which is currently commented out: https://github.com/bmlt-enabled/bmlt-root-server/blob/main/src/resources/js/tests/Login.spec.ts#L129

If you uncomment it there will be an error message
`TODO show error dialog The request failed and the interceptors did not return an alternative response`
I think it's some interaction between the router, this particular page, and rendering this particular page in unit tests; but I'm not sure.  The existing Service Bodies tests just go straight to the ServiceBodyForm or ServiceBodyModal so they aren't going to encounter this.

This isn't blocking anything, so not urgent to figure it out ... but it's annoying!

**Comment by pjaudiomv** [comment]
holy crap this is annoying, just took a quick look. doesn't make sense
